change in workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: "3.10"
+        python-version: "3.8"
 
     - name: Install dependencies
       run: |
@@ -30,19 +30,22 @@ jobs:
 
     - name: Run affected tests
       run: |
-        # Get the list of changed Python files in the pull request
-         changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^tests/.*\.py$')
+          # Get the list of changed Python files in the pull request
+          changed_files=$(git diff --name-only 8c50df5a2118d62881ed5d1ce26b8e5f6d062379 | grep '^tests/.*\.py$')
       
           # Print changed files for debugging
           echo "Changed Files: $changed_files"
-         
+      
           # Check if there are changes
           if [ -n "$changed_files" ]; then
             # Run tests for the changed files
             python -m pytest -k "$(echo "$changed_files" | tr '\n' ' ')"
+            # Print the exit code for debugging
+            echo "Exit Code: $?"
           else
             echo "No Python files in tests folder changed. Skipping tests."
           fi
+      
       
     
         
